### ISSUE TITLE
[deployer] remote-target-template.yaml should accept a {{ssh_private_key_path}} param

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#1553]
https://github.com/craftercms/deployer/blob/master/src/main/resources/templates/targets/remote-target-template.yaml. Should accept an `ssh_private_key_path` param and generate config like the following:

```
    pipeline:
      - processorName: gitPullProcessor
        remoteRepo:
          url: ...
          branch: ...
          ssh:
            privateKey:
              path: SSH_PRIVATE_KEY_PATH
```

Update also the doc in /developers/projects/deployer/api/target-management/create-target.html to indicate this new param.
