### ISSUE TITLE
[studio] BadCredentials appears in log even though auth headers is disabled

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#2555]
### Expected behavior

If authentication headers provider is defined in the auth chain, but is disabled, then not headers authentication is performed and the chain continues.

### Actual behavior

Even if the authentication headers is disabled, a `BadCredentials` exception is thrown by the `StudioAuthenticationTokenProcessingFilter`.

### Steps to reproduce the problem
* Add the following auth chain to studio-config-override.yaml:
```
studio.authentication.chain:
  # Authentication provider type
  - provider: HEADERS
    # Authentication via headers enabled
    enabled: false
    # Authentication header for secure key
    secureKeyHeader: secure_key
    # Authentication headers secure key that is expected to match secure key value from headers
    # Typically this is placed in the header by the authentication agent, e.g. Apache mod_mellon
    secureKeyHeaderValue: secure
    # Authentication header for username
    usernameHeader: username
    # Authentication header for first name
    firstNameHeader: firstname
    # Authentication header for last name
    lastNameHeader: lastname
    # Authentication header for email
    emailHeader: email
    # Authentication header for groups: comma separated list of sites and groups
    #   Example:
    #   site_author,site_xyz_developer
    groupsHeader: groups
# Authentication provider type
  - provider: DB
    # Authentication via DB enabled
    enabled: true
````
* Start/restart Studio and tail `catalina.out`
* Go to http://localhost:8080/studio

Note that in the log you get a `BadCredentialsException`, as shown in the attached stack trace

### Log/stack trace (use https://gist.github.com)

https://gist.github.com/avasquez614/b65aa9c988048620f63c828d67497e30
