### ISSUE TITLE
[studio] Cluster initialization fails when authentication type is none and username is not setup in the override config

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#2688]
## Describe the bug
Cluster initialization fails when authentication type is set to none and username is not setup in the override config.  There's a typo too in the bean name('clusterNodeRegistraition').

## To Reproduce
1. Setup clustering in the override config file, set authentication type to `none` and do not uncomment the `username`:
```
##################################################
##                 Clustering                   ##
##################################################
# Sandbox Sync Job interval
studio.clustering.sandboxSyncJob.interval: 5000
# Published Sync Job interval
studio.clustering.publishedSyncJob.interval: 60000
# Cluster node registration data
studio.clustering.node.registration:
#  cluster member local IP (reachable to other cluster members)
  localIp: 127.0.0.1
#  authentication type to access local repository
#  possible values
#   - none (no authentication needed)
#   - basic (username/password authentication)
#   - token (authentication with security token)
#   - key (ssh authentication)
  authenticationType: none
#  username to access local repository
#  username: user
#  password to access local repository
#  password: SuperSecurePassword
#  security token to access local repository
#  token: token
#  private key to access local repository (multiline string)
#  privateKey: |
#    -----BEGIN PRIVATE KEY-----
#    privateKey
#    -----END PRIVATE KEY-----
```
2. stop then start your Studio install and watch the logs.
3. Notice the error: **[ERROR] 2018-12-10 00:54:59,243 [localhost-startStop-1] [context.ContextLoader] | Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clusterNodeRegistraition' defined** 

4. Also notice the typo for the bean name in the logs:

Error creating bean with name **clusterNodeRegistraition** defined in class path resource [crafter/studio/studio-services-context.xml]

## Expected behavior
When authentication type is set to `none`, cluster setup should succeed without having to setup a username in the override config file.

It would be nice to fix the typo in the bean name too.

## Screenshots
N/A

## Logs
https://gist.github.com/alhambrav/bfd24ec685d7667762a91f8ea54fe246

### Version
Software version if applicable (copy paste from Help > About).

### OS
OS X

### Browser
N/A

## Additional context
N/A
