### ISSUE TITLE
[studio] Add support for parameters in blueprints

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#3002]
Add a section in the blueprint YAML file with a list of parameters used in the configuration files and replace them during site creation.

Example:

Blueprint YAML:

```yaml
params:
  - name: appId
    type: string # could be used for displaying a different control in the ui
    required: true # could be used to enable/disable site features if optional
  - name: appKey
```

Site Config:
```xml
<site>
  ...
  <app>
    <id>{params.appId}</id>
    <key>{params.appKey}</id>
</site>
```

When the blueprint is selected Studio should show an additional step in the create site dialog to provide a value for all required parameters.
