### ISSUE TITLE
[studio] Issue in configuring Studio for headers-based authentication

### ISSUE THREAD

**Issue by mohdnajdy** [craftercms/craftercms#3265]
## Describe the bug
I have following the documentations https://docs.craftercms.org/en/3.1/system-administrators/security/configure-headers-based-auth.html#configure-studio-for-headers-based-authentication to configure studio for header based authentication and it did not work. 

I had to follow the Chained Configuration for authentication for it to work.
https://docs.craftercms.org/en/3.1/system-administrators/activities/security/configure-studio-security.html?highlight=chain#authentication-chaining

Yet when i got it to work. The logout button did not appear. after some search in the craftercms code i found out that i still have to use the non-chained configurations for the logout button to work and not as described in the docs. 

This is what was described in the chained configuration which did not work:
```
logoutEnabled: true
    # If logout is enabled for headers authenticated users (SSO), set the endpoint of the SP or IdP logout, which should
    # be called after local logout. The {baseUrl} macro is provided so that the browser is redirected back to Studio
    # after logout (https://STUDIO_SERVER:STUDIO_PORT/studio)
logoutUrl: /saml/logout?ReturnTo={baseUrl}
```

This is what worked for me:
```
studio.authentication.headers.logout.enabled: true
studio.authentication.headers.logout.url: /saml/logout?ReturnTo={baseUrl}
```

After i configured everything the logout button only works when i am previewing a site. when i am outside on the administrative page aka `users, groups, cluster, etc..` the logout button did not work. Within the site when i click logout it logs me out but it gives me 404 bad request.

so in summary the problems are:

1. Wrong documentation where maybe it was meant for older versions.
2. fields logoutEnabled, logoutUrl in the chained configuration do not work.
3. logout button do not work on the page where system_admin manage sites, users, groups, etc..
4. after logging out i am redirected to 
```
/saml/postResponse
404 Bad Request
Your browser sent a request that this server could not understand.
```

## To Reproduce
1. follow this docs https://docs.craftercms.org/en/3.1/system-administrators/security/configure-headers-based-auth.html#configure-studio-for-headers-based-authentication

2. for the other issues follow the correct docs. https://docs.craftercms.org/en/3.1/system-administrators/activities/security/configure-studio-security.html?highlight=chain#authentication-chaining

## Expected behavior
1. the 2 variables logoutEnabled, logoutUrl should be work in the chained configurations.
2. the logout button should be working on all pages.
3. after logging out it should redirect me back to the Idp logging page.

### Version
craftercms-authoring 3.1

### OS
Debian 9

### Browser
Firefox & Chrome

**Comment by dejan-brkic** [comment]
Done
PR
https://github.com/craftercms/studio-ui/pull/1229

**Comment by dejan-brkic** [comment]
Configuration issue I was not able to reproduce.

Proper Authentication chain config looks like this:

```
# Studio authentication chain configuration
studio.authentication.chain:
  # Authentication provider type
  - provider: HEADERS
    # Authentication via headers enabled
    enabled: true
    # Authentication header for secure key
    secureKeyHeader: secure_key
    # Authentication headers secure key that is expected to match secure key value from headers
    # Typically this is placed in the header by the authentication agent, e.g. Apache mod_mellon
    secureKeyHeaderValue: secure
    # Authentication header for username
    usernameHeader: username
    # Authentication header for first name
    firstNameHeader: firstname
    # Authentication header for last name
    lastNameHeader: lastname
    # Authentication header for email
    emailHeader: email
    # Authentication header for groups: comma separated list of sites and groups
    #   Example:
    #   site_author,site_xyz_developer
    groupsHeader: groups
    # Enable/disable logout for headers authenticated users (SSO)
    logoutEnabled: true
    # If logout is enabled for headers authenticated users (SSO), set the endpoint of the SP or IdP logout, which should
    # be called after local logout. The {baseUrl} macro is provided so that the browser is redirected back to Studio
    # after logout (https://STUDIO_SERVER:STUDIO_PORT/studio)
    logoutUrl: /saml/logout?ReturnTo={baseUrl}
  # Authentication provider type
  - provider: LDAP
    # Authentication via LDAP enabled
    enabled: false
    # LDAP Server url
    ldapUrl: ldap://localhost:389
    # LDAP bind DN (user)
    ldapUsername: cn=Manager,dc=my-domain,dc=com
    # LDAP bind password
    ldapPassword: secret
    # LDAP base context (directory root)
    ldapBaseContext: dc=my-domain,dc=com
    # LDAP username attribute
    usernameLdapAttribute: uid
    # LDAP first name attribute
    firstNameLdapAttribute: cn
    # LDAP last name attribute
    lastNameLdapAttribute: sn
    # Authentication header for email
    emailLdapAttribute: mail
    # LDAP groups attribute
    groupNameLdapAttribute: crafterGroup
    # LDAP groups attribute name regex
    groupNameLdapAttributeRegex: .*
    # LDAP groups attribute match index
    groupNameLdapAttributeMatchIndex: 0
# Authentication provider type
  - provider: DB
    # Authentication via DB enabled
    enabled: true
```
