### ISSUE TITLE
[studio] Add default values for Blueprint parameters with helper text

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#3486]
Add support for blueprint parameters having default values with helper text. This allows the developer of the BP to specify reasonable defaults and the UI will indicate that to the end-user.

Assign to UI development when done with backend.

**Comment by jdrossl** [comment]
@sumerjabri something like this?
```yaml
parameters:
  - label: Optional Parameter
     name: optionalParameter
     required: false
     description: Some useful text...
     default: some default value...
```
I can see why the text is needed, but the default value not so much since all parameters are likely to be keys or passwords. Also the backend can already handle default values directly in the files:

```xml
  <site-config>
     <optional>${plugin:optionalParameter:-someDefaultValue}</optional>
    ...
```

let me know what do you think
