### ISSUE TITLE
NPE error in catalina.out after adding new site in clustered deployment

### ISSUE THREAD

**Issue by peterpakos** [craftercms/craftercms#3527]
## Describe the bug
Cluster list is empty, new sites are not getting replicated to other nodes in the cluster

## To Reproduce
Install Crafter CMS 3.1.3 on 2 separate nodes, install MariaDB on 3rd node.

Follow Clustering Setup at https://docs.craftercms.org/en/3.1/system-administrators/activities/clustering.html

Restart Crafter CMS services.

1. Log in to any node in the cluster
2. Go to Sites -> Create Site
3. Select 'Website Editorial Blueprint'
4. Enter Site Id
5. Click on 'Review and Create' then 'Create'
6. Check other nodes, Sites is showing 'You are not a member of any site. Please contact your administrator to request access.' instead of newly created site. Log contains NPE error.

Alternatively use my Vagrant/VirtualBox environment from https://github.com/peterpakos/craftercms to quickly deploy a 3 nodes setup. 

## Expected behavior
Cluster screen showing inducted nodes, new sites syncing to other nodes, no errors in logs

## Logs
https://gist.github.com/peterpakos/c33a1e97e41f9bdd1b0e1d9e591bf4a0

### Version
```
Studio Version Number: 3.1.3-f0965e
Build Number: f0965eda2807328cd26c1c8359fd3b32ddfb80f9
Build Date/Time: 09-09-2019 23:03:30 +0100
```

### OS
CentOS Linux release 7.7.1908 (Core)

### Browser
Chrome  77.0.3865.120-1

**Comment by sumerjabri** [comment]
@peterpakos In order to better help, please answer the question:
Does it eventually resolve? The database is immediately visible to all cluster nodes, but the local git repos take some time to sync (especially the first time) if you were to wait, does it eventually work on all cluster nodes?

Notes:
- We will provide better information when the `role-mappings-config.xml` is not found (or any other file) instead of an NPE: https://github.com/craftercms/craftercms/issues/3528
- We are working on a better self-clustering setup using the embedded DB, see this ticket: https://github.com/craftercms/craftercms/issues/3496
- We do still have the problem of a created site not being visible across the whole cluster until the underlying repos have been created/synced. We may need to just hide the site from all cluster nodes that haven't quite caught up yet. We will tackle this issue here: https://github.com/craftercms/craftercms/issues/3529

**Comment by peterpakos** [comment]
@sumerjabri how long does it normally take? I've waited 30-60 minutes but nothing happened. I don't recall any activity in the logs either.

**Comment by sumerjabri** [comment]
@peterpakos It should only take a few seconds to minutes (just to clone the git repos on the cluster nodes), please validate:
1. Cluster nodes are able to access one another over SSH (you can try manually)
2. You can go on disk to `$CRAFTER_HOME/data/repos/sites/` and see that what's on the node where you created the site is present on other nodes, if not, it means they're not able to clone/pull from one another

Feel free to join us on Slack for a more immediate/direct communication to resolve the issue: https://join.slack.com/t/craftercms/shared_invite/enQtNDg0NzI3NzA0NjMwLWZmMGQzMDViMzA5NDE1YjMzM2M1N2JlOWJlZDA1MjA2MGJlZjgzNDVlMmI5ODQxNmNjMWQ3NzA5ZWNkN2UxOWE

**Comment by peterpakos** [comment]
For 1. do the nodes need passwordless ssh setup between them? If so, I don't think I have seen that being a requirement anywhere in the docs. If not, how would they auth over ssh if they're not aware of other nodes' a) password and b) ssh keys?

**Comment by sumerjabri** [comment]
The documentation needs to be clearer, we will fix that.

Yes, the nodes must communicate with one another. The idea here is: A node register itself in the cluster, and all other nodes will honor that registration and `pull` from this node using the mechanism it specifies (SSH is easiest).

Here is the magic section:

```
# Cluster member registration, this registers *this* server into the pool
# Cluster node registration data, remember to uncomment the next line
studio.clustering.node.registration:
#  this server's local address (reachable to other cluster members)
  localAddress: ${env:CLUSTER_NODE_ADDRESS}
#  authentication type to access this server's local repository
#  possible values
#   - none (no authentication needed)
#   - basic (username/password authentication)
#   - key (ssh authentication)
  authenticationType: basic
#  username to access this server's local repository
  username: user
#  password to access this server's local repository
  password: SuperSecurePassword
#  private key to access this server's local repository (multiline string)
#  privateKey: |
#    -----BEGIN PRIVATE KEY-----
#    privateKey
#    -----END PRIVATE KEY-----
```

Each node fills the above with its own configuration as to how to reach *it*. All other nodes will use the above to reach this one node and pull from it.

A node may register itself using any authentication mechanism, and other nodes will follow what it says to connect to it and pull from it.

Try it out and let me know how it goes.
