### ISSUE TITLE
[studio] UM should provide a way to indicate the minimum version required

### ISSUE THREAD

**Issue by jdrossl** [craftercms/craftercms#4272]
The pipeline configuration should support a minimum version required and fail if an unsupported version is being used

```yaml
pipelines:
  system:
     requires: '>= 3.1.9'
     ...
```
