### ISSUE TITLE
[studio] Cluster doesn't work with HTTPs repo URLs and basic auth

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#4561]
## Describe the bug
When setting up a Studio cluster where the Git repos sync through HTTPS and basic authentication, Studio complains that there's not a credentials provider available.

## To Reproduce
1. Setup a 2 node Studio cluster, using HTTPS instead of SSH for Git communication. For authentication use basic auth. The config should look similar to the following:

```
##################################################
##                 Clustering                   ##
##################################################
# -------------------------------------------------------------------------------------
# IMPORTANT: When enabling clustering, please specify the following Spring profiles
# in your crafter-setenv.sh depending on the DB:
#  - SPRING_PROFILES_ACTIVE=crafter.studio.externalDb if you want to use an external DB
#  - SPRING_PROFILES_ACTIVE=crafter.studio.dbCluster if you want Studio to cluster 
#    the embedded MariaDB with other Studios' embedded MariaDBs. You will need to 
#    uncomment the Hazelcast and Galera property sections too
# -------------------------------------------------------------------------------------

# Cluster Git URL format for synching members. 
# - Typical SSH URL format: ssh://{username}@{localAddress}{absolutePath}
# - Typical HTTPS URL format: https://{localAddress}/repos/sites
# studio.clustering.sync.urlFormat: ssh://{username}@{localAddress}{absolutePath}
studio.clustering.sync.urlFormat: https://{localAddress}/git

# Cluster Syncers
# Cluster member after heartbeat stale for amount of minutes will be declared inactive
# studio.clustering.heartbeatStale.timeLimit: 5
# Cluster member after being inactive for amount of minutes will be removed from cluster
# studio.clustering.inactivity.timeLimit: 5

# Cluster member registration, this registers *this* server into the pool
# Cluster node registration data, remember to uncomment the next line
studio.clustering.node.registration:
#  This server's local address (reachable to other cluster members). You can also specify a different port by 
#  attaching :PORT to the adddress (e.g 192.168.1.200:2222)
 localAddress: ${env:CLUSTER_NODE_ADDRESS}
#  Authentication type to access this server's local repository
#  possible values
#   - none (no authentication needed)
#   - basic (username/password authentication)
#   - key (ssh authentication)
 authenticationType: basic
#  Username to access this server's local repository
 username: ${env:CLUSTER_USERNAME}
#  Password to access this server's local repository
 password: ${env:CLUSTER_PASSWORD}
#  Private key to access this server's local repository (multiline string)
#  privateKey: |
#    -----BEGIN PRIVATE KEY-----
#    privateKey
#    -----END PRIVATE KEY-----
```

2. Start the cluster.
3. Create a site based on Editorial.

You should notice the sync cluster errors, like the one attached.

## Expected behavior
There should be no sync cluster errors,

## Logs
https://gist.github.com/avasquez614/51ab969afdb22ec2da4d680e70ce9e8f
