### ISSUE TITLE
[docs] Docker compose mount the authoring site repositories is incomplete

### ISSUE THREAD

**Issue by VadimKirilchuk** [craftercms/craftercms#4896]
## Describe the bug
Some guide proposes to use [setup site for delivery](https://docs.craftercms.org/en/3.1/system-administrators/activities/delivery/setup-site-for-delivery.html)
`usage: init-site [options] [site] [repo-path]`
However, the init-site.sh which comes from the repo calls
[docker compose init site](https://github.com/craftercms/docker-compose/blob/master/scripts/init-site.sh)

Is not the exactly same thing.

Under the hood the latter is doing
```
pushd ../delivery
docker-compose exec deployer \
  gosu crafter ./bin/init-site.sh $SITE_NAME /data/authoring/repos/sites/$SITE_NAME/published
popd
```
So, it completely ignores the repo-path...
And uses /data/authoring/repos/sites/$SITE_NAME/published instead.

Which means that if you bind-mount docker volume in the authoring docker-compose
- ~/WORK/repo/crafterCMS/sites:/opt/crafter/data/repos/sites
You need to do the exactly same thing in the delivery docker-compose for deployer as well...
Otherwise it won't find a repo in the data/authoring/repos/sites...

- ~/WORK/repo/crafterCMS/sites:/data/authoring/repos/sites

Also, it's questionable if any other data from /data/authoring is really needed and if 
crafter_authoring_data:/data/authoring is required anywhere in the delivery docket-compose

## To Reproduce
1. Follow the instructions on https://github.com/craftercms/docker-compose
2. Mount the Authoring site repositories directory to a host directory
3. Create site using crafter studio (let's say the name of the site is test)
4. Start delivery docker-compose
5. Run script in the docker-compose/scripts folder called init-site. `init-site test`

## Expected behavior
Deployer target is created and any published changes are deployed to the crafter engine

**Comment by avasquez614** [comment]
@phuongnq please check if the Docker Compose `init-site.sh` script can be fixed or if we have to document the limitations.

**Comment by phuongnq** [comment]
@avasquez614 I can run `init-site.sh test` with following configuration:

* On `authoring/docker-compose.yml`:

```
# Copyright (C) 2007-2019 Crafter Software Corporation. All Rights Reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    ports:
      - 9201:9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xss1024K -Xmx1G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - elasticsearch_logs:/usr/share/elasticsearch/logs
  tomcat:
    image: craftercms/authoring_tomcat:3.1.17 # craftercms version flag
    depends_on:
      - elasticsearch
      - deployer
    ports:
      - 8080:8080
    volumes:
      - crafter_data:/opt/crafter/data
      - crafter_logs:/opt/crafter/logs
      - crafter_temp:/opt/crafter/temp
      # Elastic Search dirs needed for backup/restore
      - elasticsearch_data:/opt/crafter/data/indexes-es
    environment:
      - DEPLOYER_HOST=deployer
      - DEPLOYER_PORT=9191
      - ES_HOST=elasticsearch
      - ES_PORT=9200
  deployer:
    image: craftercms/deployer:3.1.17 # craftercms version flag
    depends_on:
      - elasticsearch
    ports:
      - 9191:9191
    volumes:
      - crafter_data:/opt/crafter/data
      - crafter_logs:/opt/crafter/logs
      - crafter_temp:/opt/crafter/temp
    environment:
      - TOMCAT_HOST=tomcat
      - TOMCAT_HTTP_PORT=8080
      - ES_HOST=elasticsearch
      - ES_PORT=9200
volumes:
  elasticsearch_data:
    name: crafter_authoring_data_elasticsearch
  elasticsearch_logs:
    name: crafter_authoring_logs_elasticsearch
  crafter_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/pnguyen/Downloads/tmp/crafter-site/data
    name: crafter_authoring_data
  crafter_logs:
    name: crafter_authoring_logs
  crafter_temp:
    name: crafter_authoring_temp
```

Note that the change is for volume `crafter_data`: `/home/pnguyen/Downloads/tmp/crafter-site/data` is a location on host machine.

```
  crafter_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/pnguyen/Downloads/tmp/crafter-site/data
    name: crafter_authoring_data
```

Then follow the above steps:

1. Follow the instructions on https://github.com/craftercms/docker-compose
2. Mount the Authoring site repositories directory to a host directory (**as above**)
3. Create site using crafter studio (let's say the name of the site is test) (**Make sure to publish `test` site first**)
4. Start delivery docker-compose
5. Run script in the docker-compose/scripts folder called `init-site.sh test`

Delivery has the site and can be accessed  using http://localhost:9080

![authoring_bulk_publish](https://user-images.githubusercontent.com/2996543/132819535-c19e299d-c8e0-4ded-9a98-6d36031d11b8.png)



![publish_command](https://user-images.githubusercontent.com/2996543/132819357-71e4383d-f9ca-431b-9504-81e724234125.png)

![delivery_site_published](https://user-images.githubusercontent.com/2996543/132819413-42f8237a-3a24-40bd-ab44-5efd83ba7a55.png)

![delivery_site](https://user-images.githubusercontent.com/2996543/132819458-edb719f6-fed4-4106-acbe-7f93d6961532.png)
