### ISSUE TITLE
[studio] Update OAS doc

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#4955]
## Describe the bug
Out of date, API 2 Spec for example `SandboxItem.availableActions`(left) compared to the AA in `DetailedItem.availableActions`(right). Please update. 
![image](https://user-images.githubusercontent.com/6722074/130242945-72dc8021-a641-4590-a804-6e72f45e2ce9.png)

### Version
`4.0.0.`

**Comment by yacdaniel** [comment]
@dejan-brkic should the parameter of `id` in all of the get Content API's(path, child, sandbox and so on) be defined as Integer? right now we have it as String

```
  /content/item_by_id:
    get:
      tags:
        - content
      summary: Get content item for given item id
      description: 'Required permission "get_detailed_item" and "read_item" and "site member"'
      operationId: getDetailedItemById
      parameters:
        - name: siteId
          in: query
          description: site ID
          required: true
          schema:
            type: string
        - name: id
          in: query
          description: item identifier
          required: true
          schema:
            type: string
```

If so please update when needed.
