### ISSUE TITLE
[studio] Authentication chain with LDAP/DB fails to continue to DB provider. 

### ISSUE THREAD

**Issue by yacdaniel** [craftercms/craftercms#5000]
#### Crafter CMS Version
`4.0.0-SNAPSHOT`

#### Describe the bug
When setting up an authentication chain with LDAP/DB and the user tries to login with a DB user, Studio tries to find the user in LDAP but it fails and doesn't continue to the DB user. 

#### To Reproduce
1. Set up auth chain https://docs.craftercms.org/en/4.0/system-administrators/activities/security/configure-authentication-chain.html, LDAP and DB 
```
studio.authentication.chain:
  # Authentication provider type
  - provider: LDAP
    # Authentication via LDAP enabled
    enabled: true
    # LDAP Server url
    ldapUrl: ldap://localhost:10389
    # LDAP bind DN (user)
    ldapUsername: uid=admin, ou=system
    # LDAP bind password
    ldapPassword: secret
    # LDAP base context (directory root)
    ldapBaseContext: dc=example,dc=com
    # LDAP username attribute
    usernameLdapAttribute: uid
    # LDAP first name attribute
    firstNameLdapAttribute: cn
    # LDAP last name attribute
    lastNameLdapAttribute: sn
    # Authentication header for email
    emailLdapAttribute: mail
    # LDAP groups attribute
    groupNameLdapAttribute: ou
    # LDAP groups attribute name regex
    groupNameLdapAttributeRegex: .*
    # LDAP groups attribute match index
    groupNameLdapAttributeMatchIndex: 0
  - provider: DB
    # Authentication via DB enabled
    enabled: true
```
2. Try to log in with DB user `admin` for example
3. See error

Now if I put DB provider first and then LDAP, DB login works but If i try to login with LDAP is looking for the user in DB. 

#### Logs
`[INFO] 2021-09-10T09:40:37,404 [http-nio-8080-exec-2] [listener.AuditLoginListener] | Failed to authenticate user admin logging in from IP: 127.0.0.1. Reason: User admin not found in LDAP server`

#### Screenshots
{{If applicable, add screenshots to help explain your problem.}}

**Comment by yacdaniel** [comment]
@jdrossl please check the next stacktrace, when DB is first and then LDAP in auth chain
```
studio.authentication.chain:
  - provider: DB
    # Authentication via DB enabled
    enabled: true
  # Authentication provider type
  - provider: LDAP
    # Authentication via LDAP enabled
    enabled: true
    # LDAP Server url
    ldapUrl: ldap://localhost:1389
    # LDAP bind DN (user)
    ldapUsername: cn=admin,dc=example,dc=org
    # LDAP bind password
    ldapPassword: adminpassword
    # LDAP base context (directory root)
    ldapBaseContext: dc=example,dc=org
    # LDAP username attribute
    usernameLdapAttribute: uid
    # LDAP first name attribute
    firstNameLdapAttribute: cn
    # LDAP last name attribute
    lastNameLdapAttribute: sn
    # Authentication header for email
    emailLdapAttribute: mail
    # LDAP groups attribute
    groupNameLdapAttribute: ou
    # LDAP groups attribute name regex
    groupNameLdapAttributeRegex: .*
    # LDAP groups attribute match index
    groupNameLdapAttributeMatchIndex: 0
```
 if an user tries to login from LDAP, Studio log shows that only DB provider is used and never entered the LDAP auth provider.

https://gist.github.com/yacdaniel/228e9d700f128137b97a0d79dc15e8a0
