### ISSUE TITLE
[studio] Publish stuck when trying to delete a folder with items that was cut/paste previously

### ISSUE THREAD

**Issue by avasquez614** [craftercms/craftercms#5498]
#### Crafter CMS Version
Latest 4.0.0 SNAPSHOT build

#### Date of Build
04/13

#### Describe the bug
Publish fails with the error posted below when copy/pasting, then cut/pasting, and then deleting a folder with items.

#### To Reproduce
1. Create a site based on Editorial
2. Copy the articles folder (with children) and paste it in the same folder
3. Cut/paste the copy of the articles folder under one of the categories page (Entertainment, Style, etc)
4. Delete the copy
5. See the error

This issue is not happening in 3.1 btw. After inspecting the code, the issue occurs because when deleting the files that were cut, publish requests are generated with the original path of the item, before the cut:

```
               id: 51
             site: ed5
      environment: live
             path: /site/website/entertainment/articles-copy-1/2020/12/top-books-for-young-women/index.xml
          oldpath: /site/website/articles-copy-1/2020/12/top-books-for-young-women/index.xml
         username: admin
    scheduleddate: 2022-04-12 18:34:49
            state: PROCESSING
           action: DELETE
 contenttypeclass: page
  submission_type: NULL
submissioncomment: 
        commit_id: 06a598bc2b4650ae415f47d2ff95c1057576d1b7
       package_id: 45dba999-91be-42fc-86f6-dbc6f2ae50a2
            label: NULL
     published_on: NULL
```
Studio then sees this old path and tries to delete it. This doesn't happen in 3.1, where the old paths after the cut are actually null.

#### Logs
https://gist.github.com/avasquez614/1354fc5b04cf877bd167713d73ef3a50
