### ISSUE TITLE
Make deployer `GitPullProcessor` `pull` options and `merge strategies` configurable

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#7617]
### CI Number

5467

### Latest version

- [x] The issue is in the develop branch
- [x] The issue is in the latest released 4.2.x
- [ ] The issue is in the latest released 4.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Today, the deployer `GitPullProcessor` operates with default options and merge strategies of `theirs` 
In some operational environments, it may be advantageous or desirable to change the behavior to use a different strategy or other options  on the pull (fast forward only, force, and so on.)

### Describe the solution you'd like

Make the pull options and merge strategy for the deployer's `GitPullProcessor` configurable. Alternatively, limit the ability to directly set options with specific switches for particular options/behaviors.

Common use case:

**Possible pull mechanics:**
- Force pull from the remote. If the commit ID on hand does not exist in the repo, diff from the beginning: This covers re-deploying a site with a modified (typically truncated) history.
- Only pull when fast forwarding: If the remote has out of order commits (new commits from a previous point in time) do not pull

**Possible Merge strategies:**
In the case of a merge conflict we MUST resolve the issue as conflicted content can cause an issue.  Today the option is to always trust the remote. Allow the deploy to be configured to keep what it has instead.  Use of this option should not be considered the default and should only be configured when/where it makes sense.

**Comment by jmendeza** [comment]
Added new options to gitPullProcessor:
```
    - processorName: gitPullProcessor
      fastForwardMode: FF_ONLY
      contentMergeOption: CONFLICT
      mergeStrategy: theirs
      remoteRepo:
        url: ......../repos/sites/ed1/published
        branch: live
```
*fastForwardMode:* The fast forward mode to use when pulling changes from the remote repo. Supported values are: `FF`, `NO_FF`, `FF_ONLY`. Default is `FF`. See [jgit docs](https://javadoc.io/static/org.eclipse.jgit/org.eclipse.jgit/7.1.0.202411261347-r/org.eclipse.jgit/org/eclipse/jgit/api/MergeCommand.FastForwardMode.html)
*mergeStrategy:* The merge strategy to use. Supported values are: `ours`, `theirs`, `simple-two-way-in-core`, `resolve`, `recursive`. Default is `theirs`. See [jgit docs](https://javadoc.io/static/org.eclipse.jgit/org.eclipse.jgit/7.1.0.202411261347-r/org.eclipse.jgit/org/eclipse/jgit/merge/MergeStrategy.html)
*contentMergeOption:* The content merge strategy to handle conflicts. Supported values are `CONFLICT`, `OURS`, `THEIRS`, `UNION`. Default is `CONFLICT`. See [jgit docs](https://javadoc.io/static/org.eclipse.jgit/org.eclipse.jgit/7.1.0.202411261347-r/org.eclipse.jgit/org/eclipse/jgit/merge/ContentMergeStrategy.html)


Added new `failedProcessors` option to mailNotificationProcessor:
```
    - processorName: mailNotificationProcessor
      subject: Deployment error
      status: ON_TOTAL_FAILURE
      failedProcessors: gitPullProcessor
      templateName: deployment-error
      to:
      - test@example.com
```
`failedProcessors` is a regex to match the failing processor name. In the example above it will only send emails for deployments where `gitPullProcessor` has failed.


Pending: limit frequency of failure notifications.

**Comment by jmendeza** [comment]
Added options to mailNotificationProcessor:
```
    - processorName: mailNotificationProcessor
      to:
      - test@example.com
      mutePeriodMinutes: 2
      lastDateFilenameSuffix: -error
....
```
*mutePeriodMinutes:* wait this number of minutes to send another email notification for this target. Default is `0`
*lastDateFilenameSuffix:* Suffix for the file to keep track of the last email timestamp. This will allow to have multiple notification processors for the same target. Default is `-lastNotification`
Filename will be targetId + processor name + suffix. e.g.:
`ed1-default-mailNotificationProcessor-lastErrorNotification`
