### ISSUE TITLE
Drop the `patch` number from extension compatibility

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#7689]
### Latest version

- [x] The issue is in the develop branch
- [x] The issue is in the latest released 4.2.x
- [ ] The issue is in the latest released 4.1.x

### Duplicates

- [x] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

Specifying the compatibility list for extensions down to the `patch` level is no longer necessary because of the product stability. Within a `minor` release, things no longer change in such a way as to make an extension unstable. Maintaining the compatibility list is too much work, with little return now.

### Describe the solution you'd like

Trim the compatibility matrix to `major` and `minor` versions only in:
* MP
* Studio
* Plugins
* Blueprints

MP will keep the database field `patch` but will not use it. We will select the most recent extension that matches the `major.minor` version of the requesting client (studio). Crafter Studio can continue to send `patch`, but MP can ignore it.

For MP, we can then update the code such that we don't need to keep adding `patch` numbers to accept registration of new extensions. The MP and Studio must still work with the old extensions, and new extensions will come in with the "missing" `patch` number, but still work.

We will then update the `craftercms-plugin.yaml` for _future_ extensions to remove the `patch` number.

This will make maintaining these much easier.

This precedes the ticket: https://github.com/craftercms/craftercms/issues/6192

**Comment by phuongnq** [comment]
@sumerjabri The PR updates MP so that when searching plugins, we ignore the patch number. We still need to send a full Crafter version using the API and the `patch` will be ignored, which I do not see an issue with the current Studio (but please let me know if we want to support sending the version with only `major` and `minor` values when searching for compatible plugins).

In the plugin descriptor, we can use the full crafter version number or the short version with only `major` and `minor` numbers but we should not mix them in a plugin version.

For example:

* Plugin version `1.0.0` can have:
```
  crafterCmsVersions:
    - major: 3
      minor: 1
      patch: 0
    - major: 3
      minor: 1
      patch: 1
    - major: 4
      minor: 2
      patch: 0
    - major: 4
      minor: 2
      patch: 1
```
* Then in plugin version `1.0.1` we can have:
```
  crafterCmsVersions:
    - major: 3
      minor: 2
    - major: 4
      minor: 2
```

But we should not mix them in a plugin version. This is because in the DB, an empty `patch` will insert the value `0` so mixing them in a plugin will cause the constraint foreign key to be duplicated.
