### ISSUE TITLE
Add Worker Thread Supervisor to Deployer

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#8153]
### CI Number

5753

### Duplicates

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Typically, the Deployer's worker threads are allocated and complete their work quickly (seconds or minutes at the extremes). It is currently assumed that each step taken by the worker thread (built in or configured through out-of-the-box or custom processors) will detect its errors and report them. This generally works well.

However, one of the steps may become stuck for some reason that blocks or hinders the worker in a way that prohibits it from detecting that it is "hung". An observed example of this is a NIO4J file operation that makes a native operating system call that does not return or time out.

A mechanism that sits outside of the worker is required to monitor the worker and can raise progress/status and alarm events.

### Describe the solution you'd like

Add a worker thread supervisor mechanic that:
- Can be configured "time out" duration for a status update period that is overridable per target, such that if a status update is not received within this period, an alarm event is raised.
- Can receive status updates from work threads
- Out of the box alarm event handlers
  -  Send email
  - Call webhook 
  - Possible: Support configuring/calling event handlers for regular status updates in addition to alarm events

**Comment by russdanner** [comment]
Note: We will probably need a `4.4` for this.

**Comment by avasquez614** [comment]
### Pre-requisites for solution

1. Deployments will have a runtime warning threshold that basically indicates that a deployment has been running for quite a long time and a warning should be triggered. This should be configurable through the target (`Target.getRuntimeWarningThreshold`). By default the threshold should be an hour.
2. Targets will now have event listeners. These should be configurable through the YAML, similar to lifecycle hooks.
3. Initial event to implement will be `DeploymentRuntimeWarningEvent`.
4. Initial event handlers:
    1. `EmailNotificationEventListener`
    2. `WebhookEventListener`

### Proposed Solution

A `DeploymentRuntimeSupervisor` can be implemented the following way:

1. It runs as a cron job that wakes up every X minutes.
2. When it wakes up, it gets the list of all Targets and checks if they have a Deployment running (`Target.getCurrentDeployment`)
3. Checks the start time of the Deployment (`Deployment.getStart()`). 
4. If the current time - start time is greater that the configured runtime warning threshold (`Target.getRuntimeWarningThreshold`), then the supervisor triggers a `DeploymentRuntimeWarningEvent`, log the event and calls the event listeners associated to `RuntimeWarningEvent` for the target.

**Comment by jmendeza** [comment]
Added new properties to application.yaml to enable and configure the cron job for the deployment supervisor. By default it runs every 10 minutes:
```
deployer:
   main:
      deployments:
            # Configuration for the deployment supervisor
            supervisor:
                enabled: true
                cron: '0 */10 * * * ?'
```

The target runtime threshold can be configured using `target.runtimeWarningThreshold.seconds` property, default is 1 hour. Also, the webhook configuration now accepts a timeout:
```
target:
    runtimeWarningThreshold:
        # The threshold in seconds to warn about long-running deployments
        seconds: 3600
    notifications:
        webhook:
            # The timeout in milliseconds for the webhook requests
            timeout: 30000
```

New `eventListeners` configuration in the target yaml file. 
```
target:
   eventListeners:
        -   eventName: deploymentRuntimeWarning  # This is the type of event to handle
            listeners:
            -   name: notificationEventListener
                templateName: runtime-warning
                sender: emailNotificationSender
                to: admin@test.com
            -   name: notificationEventListener
                sender: webhookNotificationSender
```
The `notificationEventListener` requires the properties:
- `templateName`: freeMarker template to render the message. Notice that the actual path of the template file will depend on the sender. For webhook it uses `target.notifications.webhook.templates.location`,  for email `target.notifications.webhook.templates.location`
-  `sender`: actual message sender, currently supported: `webhookSender` or `emailSender`
Additionally, it accepts configuration properties for the message sender, e.g.:

```
-   name: notificationEventListener
    templateName: runtimeWarning
    from: alerts@test.com
    to: admin@test.com  # REQUIRED
    subject: Runtime threshold reached
-   name: notificationEventListener
    templateName: runtimeWarning
    url: <THE WEBHOOK URL>  # REQUIRED
    method: GET
    contentType: text/plain
    
```
